[colors]
foreground = "#99d1ce"
background = "#11151c"
cursor_bg = "#99d1ce"
cursor_border = "#99d1ce"
cursor_fg = "#11151c"
selection_bg = "#0e232e"
selection_fg = "#99d1ce"
split = "#0092b6"
compose_cursor = "#d26937"
scrollbar_thumb = "#091f2e"

ansi = ["#0e1116", "#c23127", "#2aa889", "#edb443", "#0092b6", "#AB21A0", "#53b1cf", "#99d1ce"]
brights = ["#4e5166", "#e42100", "#00b894", "#ffc142", "#00a0c7", "#c700ba", "#10c3ea", "#d3ebe9"]

[colors.tab_bar]
inactive_tab_edge = "#0c1014"
background = "#11151c"

[colors.tab_bar.active_tab]
fg_color = "#0c1014"
bg_color = "#0092b6"

[colors.tab_bar.inactive_tab]
fg_color = "#1e6479"
bg_color = "#091f2e"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#0092b6"
bg_color = "#091f2e"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#0092b6"
bg_color = "#11151c"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#0092b6"
bg_color = "#11151c"

[metadata]
aliases = []
author = "folke"
name = "neogotham_dark"