[[themes]]
name = "Tokyo Night"
[themes.palette]
background = "#0c1014"
foreground = "#0a3749"
black = "#4e5166"
red = "#c23127"
green = "#2aa889"
yellow = "#edb443"
blue = "#0092b6"
magenta = "#AB21A0"
cyan = "#53b1cf"
white = "#99d1ce"
bright_black = "#11151c"
bright_red = "#f47263"
bright_green = "#4cd0ad"
bright_yellow = "#d26937"
bright_blue = "#1e6479"
bright_magenta = "#e542d7"
bright_cyan = "#00b5df"
bright_white = "#99d1ce"
